# Generated by Django 4.2.5 on 2023-09-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
