# Generated by Django 4.2.5 on 2023-09-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
